server:
  port: 80
  servlet:
    context-path: /wx01

spring:
  datasource:
    driver-class-name:  com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/weixin?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123
  redis:
    database: 0                           # Redis数据库索引（默认为0 redis有16个库）
    host: 192.168.198.148                 # Redis服务器地址
    port: 6379                             # Redis服务器连接端口
    password: 123456                      # Redis服务器连接密码（默认为空）
    jedis:                                # spirngboot1.x与2.x区别是2.x添加一个前缀jedis、1.x没有
      pool:
        max-active: 100                  # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 10                     # 连接池中的最大空闲连接
        min-idle: 0                      # 连接池中的最小空闲连接
        max-wait: -1                     # 连接池最大阻塞等待时间（使用负值表示没有限制）
    timeout:  5000                       # 连接超时时间（毫秒），不能设置为0，时间太短连接不上会报错
#  jpa:
#    database: mysql
#    show-sql: true
  freemarker:
    allow-request-override: false
    request-context-attribute:  req
    suffix: .ftl
    content-type: text/html;charset=UTF-8
    enabled:  true
    cache:  false
    template-loader-path: classpath:/templates/
    charset:  UTF-8
#  devtools:
#    restart:
#      enabled:  true                       #热部署生效
#      exclude:  WEB-INF/**                 #classpath目录下的WEB-INF文件夹内容修改不重启
#      additional-paths: src/main/java     #设置重启的目录


mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.zking.wx01.model







